### ISSUE TITLE
[*very* Minor] Typo/lack of clarity in password prompt 

### ISSUE THREAD

**Issue by isabelgiang** [HomeDivision/Choreless#18]
#"Must contain at least 1 digit and alpha and be between 6-20 characters"

This message appears at any point when the user is prompted to change their password input due to it not meeting the desired password constraints. The issue is that the desired password constraints are not clear from the instructions given.

Does alpha = alphanumerical character?
Also, doesn't mention if 6 - 20 is inclusive (which it appears to be).

**Comment by corstena** [comment]
Updated password requirements wording to be more clear
