### ISSUE TITLE
Minor: Once you sign up and create an account, it takes you back to the sign in page even though the top right says “Welcome, ______” and “SIGN OUT”.

### ISSUE THREAD

**Issue by leemeli** [HomeDivision/Choreless#19]
Minor: Once you sign up and create an account, it takes you back to the sign in page even though the top right says “Welcome, ______” and “SIGN OUT”.

Reproduction steps:
Press SIGN IN/OUT
Click on SIGN UP tab
Fill out information and click SIGN UP
Takes you back to sign in page

**Comment by jimmybnguyen** [comment]
https://github.com/HomeDivision/Choreless/issues/21
https://github.com/HomeDivision/Choreless/issues/29

**Comment by FXStrato** [comment]
Fixed in commit 978c5514cbc807391867a6b7e1fbaa1502ceabfa
