### ISSUE TITLE
Minor: Colors of chores do not change when changed in user settings.

### ISSUE THREAD

**Issue by isabelgiang** [HomeDivision/Choreless#22]
Steps to reproduce:
1. Add a chore to the Choreless weekly calendar.
2. Open the side menu.
3.  Navigate to User Settings.
4. Scroll to the bottom and click on a color different than the default color (which appears to be dark orange).
5. Return to the Weekly Calendar.

Alternatively (if chores are already added):
1. Open the side menu.
2.  Navigate to User Settings.
3. Scroll to the bottom and click on a color different than the default color (which appears to be dark orange).
4. Open the Weekly Calendar.

Unclear whether or not the color of the chores are meant to change retroactively (in other words, if the color is meant to change after they are already added to the calendar), but they do not change in either case.

**Comment by jimmybnguyen** [comment]
fixed https://github.com/HomeDivision/Choreless/commit/c78aa83ed3225aae8cedd0e481e4b95372e3f449

**Comment by bxie** [comment]
colors do not change until refresh
