### ISSUE TITLE
[minor] Can't join a group that has had all members leave

### ISSUE THREAD

**Issue by greycabb** [HomeDivision/Choreless#23]
I first created an account and group with passcode "OMWTY", this code should still work. Then I remove myself from the group. But when I create another account and attempt to join group with this passcode, it does not let me.

__
[Reproduction Steps]
1) Create a new account using "Sign Up" feature with all valid fields.

2) Click "Create", then create a group.

3) Write down the password. Click "Go to group"

4) Click the 3 bars on the top left, and then click "Group Settings".

5) Where your username is, delete yourself from your group.

6) Create a new account with a different username with "Sign Up" feature again.

7) Enter the passcode you recorded on Step 3, then attempt to join the group by clicking "Join Group" button, you will not be able to.

In the Console, I get this message twice:
`Uncaught (in promise) TypeError: Cannot read property 'push' of null
    at JoinGroupForm.js:46
    at <anonymous>
(anonymous) @ JoinGroupForm.js:46`
at JoinGroupForm.js:46

This is minor since a leader removing themselves from a group then people joining again is unlikely to occur, but it can still happen.

Browser: Google Chrome

**Comment by imdodrill** [comment]
Fixed and pushed to dev branch
