### ISSUE TITLE
[Minor] You can open up an empty chore list.

### ISSUE THREAD

**Issue by BossJ** [HomeDivision/Choreless#24]
Precondition: No chores set in account.

1. Go to calendar page for group.

2. Open add a chore menu.

3. Blank menu with a single unselectable option appears.

**Comment by FXStrato** [comment]
Add chore menu is now disabled if no chores exist, there should be no unselectable options now. 
Commit: 6de1c81151230b0d8326b90ff0bfd6f77e35d258
