### ISSUE TITLE
[Minor] Nothing in Select Chore to Add, could have default ones

### ISSUE THREAD

**Issue by DianaCondon** [HomeDivision/Choreless#26]
Upon first opening application, would be nice to have some prompted common chores, or have the drop down deactivated.

**Comment by jimmybnguyen** [comment]
When creating a group, there is a check box if you want default shores to be added. We may have to make this more noticeable.

**Comment by FXStrato** [comment]
Dropdown is deactivated if no default chores were selected to populate menu. 
Commit: 9c5390452ca60f066c3f4ad1f7e0c9738b5d5b4a
