### ISSUE TITLE
[Minor] You have to go into group settings to add chore

### ISSUE THREAD

**Issue by DianaCondon** [HomeDivision/Choreless#27]
No prompt let me know where to find how to add new chore to possible chore list.

**Comment by corstena** [comment]
Not really a bug per se, just bad user experience. Will add a notification if we have time, but this is low on our priority list.

**Comment by jimmybnguyen** [comment]
Due to the time constraints of team members, we will not be fixing this issue since it's not a bug per say, but rather a user experience issue.
