### ISSUE TITLE
sign in twice

### ISSUE THREAD

**Issue by yipang** [HomeDivision/Choreless#29]
When I'm already signin, I can still go to the homepage and sign in again.

**Comment by jimmybnguyen** [comment]
[Similar issue ](https://github.com/HomeDivision/Choreless/issues/21)

**Comment by FXStrato** [comment]
Home page is dynamic, and should not show sign/up if user is already signed in. Reference: acc2608b40f85e7ee17fd5dd025cf69dd815115a
