### ISSUE TITLE
[major] Sign up broken on chrome mobile 

### ISSUE THREAD

**Issue by sarahf95** [HomeDivision/Choreless#31]
Sign up does not work on mobile chrome. No feedback is given when the sign up form is filled out. Form functionality is in tact (validating email address and matching passwords) but an account fails to be created.

**Comment by jimmybnguyen** [comment]
Just tested this on my mobile phone--the account does get created but it does not automatically log you in. We never intended to make Choreless mobile friendly within the timeframe of the project, we'll see if we can justify fixing this bug in time.

**Comment by jimmybnguyen** [comment]
Due to the time constraints of team members, we will not be fixing this bug since mobile was not a focus for this project. Perhaps in future releases!
