### ISSUE TITLE
[Minor] Validation of users does not occur on all pages

### ISSUE THREAD

**Issue by juimin** [HomeDivision/Choreless#33]
Since the chores associated with a group are tied to URLs, having knowledge a group's URL allows you to edit their chores.

Scenarios where this might occur:
- You typed in the wrong ID
- You were in a group and left but still had it bookmarked somewhere
- If you're really evil and want to just mess with people

Tested on groups where the user has either left or was never a part of the group. Also tested on orphaned groups (no users left)

Reproduction:
- Sign in as any user
- Go to application URL /[some group id]/weekly
- The [some group id] can be any group code as long as the URL leads to a valid group that you aren't in.
- Make alterations to the chore assignments (If you are logged in as another user elsewhere you can watch this in real time)

**Comment by FXStrato** [comment]
Fixed in commit 516b9544400baf4585eff04898187cd7aac578d6
