### ISSUE TITLE
Sign in home page and re-login issue. 

### ISSUE THREAD

**Issue by jkuelz** [HomeDivision/Choreless#34]
After creating an account with the username "user" I was lead to the home page which was the same sign in/sign up page that I used to sign in (screenshot provided). I also chose to have chrome remember my password and email, but when I signed out and tried to sign back in, it gave me the error, "There is no user record corresponding to this identifier. The user may have been deleted."
1. sign up
2. remember password option on chrome
3. sign in -failure
![image](https://cloud.githubusercontent.com/assets/15003460/26806503/16d05576-4a06-11e7-8ea2-75071b03fa68.png)
![image](https://cloud.githubusercontent.com/assets/15003460/26806551/525235f6-4a06-11e7-8abd-bf4228a080e3.png)

**Comment by jimmybnguyen** [comment]
Can you please try to sign up again and see if it works, thanks. I followed your steps and did not experience this.

**Comment by jkuelz** [comment]
I just tried signing up and signing in with a different email/username and it worked! I just realized it could've been because chrome saved the "username" as the "email" the first time. So I had to re-enter that manually.

**Comment by jimmybnguyen** [comment]
If you could, please go to Settings > Advanced Settings > Manage Passwords, and see if the email was saved under Choreless. This could a pretty interesting bug.

**Comment by jimmybnguyen** [comment]
Another note: I checked Firebase and did not find a user@me.com. However, I did find a email@me.com with a username of "user." This may be the account you created

**Comment by jkuelz** [comment]
Yes, I must've copied it wrong when I had to replace it from the chrome saved password settings. Chrome saves the username I created as the email field. So it pre-populated with email field with the wrong information, and I just entered the email wrong because I have a poor memory. Sorry for the confusion. Chrome's settings are probably out of your scope.
